/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace HerbTrace {
  export type TraceEventStruct = {
    status: PromiseOrValue<string>;
    location: PromiseOrValue<string>;
    stakeholder: PromiseOrValue<string>;
    notes: PromiseOrValue<string>;
    eventTimestamp: PromiseOrValue<string>;
    blockTimestamp: PromiseOrValue<BigNumberish>;
  };

  export type TraceEventStructOutput = [
    string,
    string,
    string,
    string,
    string,
    BigNumber
  ] & {
    status: string;
    location: string;
    stakeholder: string;
    notes: string;
    eventTimestamp: string;
    blockTimestamp: BigNumber;
  };

  export type HerbBatchStruct = {
    batchId: PromiseOrValue<string>;
    farmerName: PromiseOrValue<string>;
    location: PromiseOrValue<string>;
    herbType: PromiseOrValue<string>;
    quantityKg: PromiseOrValue<BigNumberish>;
    gpsCoordinates: PromiseOrValue<string>;
    harvestDate: PromiseOrValue<string>;
    farmingMethod: PromiseOrValue<string>;
    qualityScore: PromiseOrValue<string>;
    creationTimestamp: PromiseOrValue<BigNumberish>;
    history: HerbTrace.TraceEventStruct[];
  };

  export type HerbBatchStructOutput = [
    string,
    string,
    string,
    string,
    BigNumber,
    string,
    string,
    string,
    string,
    BigNumber,
    HerbTrace.TraceEventStructOutput[]
  ] & {
    batchId: string;
    farmerName: string;
    location: string;
    herbType: string;
    quantityKg: BigNumber;
    gpsCoordinates: string;
    harvestDate: string;
    farmingMethod: string;
    qualityScore: string;
    creationTimestamp: BigNumber;
    history: HerbTrace.TraceEventStructOutput[];
  };
}

export interface HerbTraceInterface extends utils.Interface {
  functions: {
    "addTraceEvent(string,string,string,string,string,string)": FunctionFragment;
    "createHerbBatch(string,string,string,string,uint256,string,string,string,string)": FunctionFragment;
    "getHerbHistory(string)": FunctionFragment;
    "herbBatches(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addTraceEvent"
      | "createHerbBatch"
      | "getHerbHistory"
      | "herbBatches"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addTraceEvent",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createHerbBatch",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getHerbHistory",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "herbBatches",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addTraceEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createHerbBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHerbHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "herbBatches",
    data: BytesLike
  ): Result;

  events: {
    "BatchCreated(string,string,uint256)": EventFragment;
    "BatchUpdated(string,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BatchCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BatchUpdated"): EventFragment;
}

export interface BatchCreatedEventObject {
  batchId: string;
  farmerName: string;
  timestamp: BigNumber;
}
export type BatchCreatedEvent = TypedEvent<
  [string, string, BigNumber],
  BatchCreatedEventObject
>;

export type BatchCreatedEventFilter = TypedEventFilter<BatchCreatedEvent>;

export interface BatchUpdatedEventObject {
  batchId: string;
  newStatus: string;
  timestamp: BigNumber;
}
export type BatchUpdatedEvent = TypedEvent<
  [string, string, BigNumber],
  BatchUpdatedEventObject
>;

export type BatchUpdatedEventFilter = TypedEventFilter<BatchUpdatedEvent>;

export interface HerbTrace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HerbTraceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addTraceEvent(
      _batchId: PromiseOrValue<string>,
      _newStatus: PromiseOrValue<string>,
      _newLocation: PromiseOrValue<string>,
      _stakeholder: PromiseOrValue<string>,
      _notes: PromiseOrValue<string>,
      _eventTimestamp: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createHerbBatch(
      _batchId: PromiseOrValue<string>,
      _farmerName: PromiseOrValue<string>,
      _location: PromiseOrValue<string>,
      _herbType: PromiseOrValue<string>,
      _quantityKg: PromiseOrValue<BigNumberish>,
      _gpsCoordinates: PromiseOrValue<string>,
      _harvestDate: PromiseOrValue<string>,
      _farmingMethod: PromiseOrValue<string>,
      _qualityScore: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getHerbHistory(
      _batchId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[HerbTrace.HerbBatchStructOutput]>;

    herbBatches(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        string,
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber
      ] & {
        batchId: string;
        farmerName: string;
        location: string;
        herbType: string;
        quantityKg: BigNumber;
        gpsCoordinates: string;
        harvestDate: string;
        farmingMethod: string;
        qualityScore: string;
        creationTimestamp: BigNumber;
      }
    >;
  };

  addTraceEvent(
    _batchId: PromiseOrValue<string>,
    _newStatus: PromiseOrValue<string>,
    _newLocation: PromiseOrValue<string>,
    _stakeholder: PromiseOrValue<string>,
    _notes: PromiseOrValue<string>,
    _eventTimestamp: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createHerbBatch(
    _batchId: PromiseOrValue<string>,
    _farmerName: PromiseOrValue<string>,
    _location: PromiseOrValue<string>,
    _herbType: PromiseOrValue<string>,
    _quantityKg: PromiseOrValue<BigNumberish>,
    _gpsCoordinates: PromiseOrValue<string>,
    _harvestDate: PromiseOrValue<string>,
    _farmingMethod: PromiseOrValue<string>,
    _qualityScore: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getHerbHistory(
    _batchId: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<HerbTrace.HerbBatchStructOutput>;

  herbBatches(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      string,
      BigNumber,
      string,
      string,
      string,
      string,
      BigNumber
    ] & {
      batchId: string;
      farmerName: string;
      location: string;
      herbType: string;
      quantityKg: BigNumber;
      gpsCoordinates: string;
      harvestDate: string;
      farmingMethod: string;
      qualityScore: string;
      creationTimestamp: BigNumber;
    }
  >;

  callStatic: {
    addTraceEvent(
      _batchId: PromiseOrValue<string>,
      _newStatus: PromiseOrValue<string>,
      _newLocation: PromiseOrValue<string>,
      _stakeholder: PromiseOrValue<string>,
      _notes: PromiseOrValue<string>,
      _eventTimestamp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    createHerbBatch(
      _batchId: PromiseOrValue<string>,
      _farmerName: PromiseOrValue<string>,
      _location: PromiseOrValue<string>,
      _herbType: PromiseOrValue<string>,
      _quantityKg: PromiseOrValue<BigNumberish>,
      _gpsCoordinates: PromiseOrValue<string>,
      _harvestDate: PromiseOrValue<string>,
      _farmingMethod: PromiseOrValue<string>,
      _qualityScore: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getHerbHistory(
      _batchId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<HerbTrace.HerbBatchStructOutput>;

    herbBatches(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        string,
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber
      ] & {
        batchId: string;
        farmerName: string;
        location: string;
        herbType: string;
        quantityKg: BigNumber;
        gpsCoordinates: string;
        harvestDate: string;
        farmingMethod: string;
        qualityScore: string;
        creationTimestamp: BigNumber;
      }
    >;
  };

  filters: {
    "BatchCreated(string,string,uint256)"(
      batchId?: null,
      farmerName?: null,
      timestamp?: null
    ): BatchCreatedEventFilter;
    BatchCreated(
      batchId?: null,
      farmerName?: null,
      timestamp?: null
    ): BatchCreatedEventFilter;

    "BatchUpdated(string,string,uint256)"(
      batchId?: null,
      newStatus?: null,
      timestamp?: null
    ): BatchUpdatedEventFilter;
    BatchUpdated(
      batchId?: null,
      newStatus?: null,
      timestamp?: null
    ): BatchUpdatedEventFilter;
  };

  estimateGas: {
    addTraceEvent(
      _batchId: PromiseOrValue<string>,
      _newStatus: PromiseOrValue<string>,
      _newLocation: PromiseOrValue<string>,
      _stakeholder: PromiseOrValue<string>,
      _notes: PromiseOrValue<string>,
      _eventTimestamp: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createHerbBatch(
      _batchId: PromiseOrValue<string>,
      _farmerName: PromiseOrValue<string>,
      _location: PromiseOrValue<string>,
      _herbType: PromiseOrValue<string>,
      _quantityKg: PromiseOrValue<BigNumberish>,
      _gpsCoordinates: PromiseOrValue<string>,
      _harvestDate: PromiseOrValue<string>,
      _farmingMethod: PromiseOrValue<string>,
      _qualityScore: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getHerbHistory(
      _batchId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    herbBatches(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addTraceEvent(
      _batchId: PromiseOrValue<string>,
      _newStatus: PromiseOrValue<string>,
      _newLocation: PromiseOrValue<string>,
      _stakeholder: PromiseOrValue<string>,
      _notes: PromiseOrValue<string>,
      _eventTimestamp: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createHerbBatch(
      _batchId: PromiseOrValue<string>,
      _farmerName: PromiseOrValue<string>,
      _location: PromiseOrValue<string>,
      _herbType: PromiseOrValue<string>,
      _quantityKg: PromiseOrValue<BigNumberish>,
      _gpsCoordinates: PromiseOrValue<string>,
      _harvestDate: PromiseOrValue<string>,
      _farmingMethod: PromiseOrValue<string>,
      _qualityScore: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getHerbHistory(
      _batchId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    herbBatches(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
