/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace HerbTrace {
  export type HerbBatchStruct = {
    batchId: PromiseOrValue<BigNumberish>;
    farmerName: PromiseOrValue<string>;
    location: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<string>;
  };

  export type HerbBatchStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    string
  ] & {
    batchId: BigNumber;
    farmerName: string;
    location: string;
    timestamp: BigNumber;
    status: string;
  };
}

export interface HerbTraceInterface extends utils.Interface {
  functions: {
    "batchCounter()": FunctionFragment;
    "createHerbBatch(string,string)": FunctionFragment;
    "getHerbHistory(uint256)": FunctionFragment;
    "herbBatches(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "batchCounter"
      | "createHerbBatch"
      | "getHerbHistory"
      | "herbBatches"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createHerbBatch",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHerbHistory",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "herbBatches",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createHerbBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHerbHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "herbBatches",
    data: BytesLike
  ): Result;

  events: {
    "BatchCreated(uint256,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BatchCreated"): EventFragment;
}

export interface BatchCreatedEventObject {
  batchId: BigNumber;
  farmerName: string;
  timestamp: BigNumber;
}
export type BatchCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  BatchCreatedEventObject
>;

export type BatchCreatedEventFilter = TypedEventFilter<BatchCreatedEvent>;

export interface HerbTrace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HerbTraceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    createHerbBatch(
      _farmerName: PromiseOrValue<string>,
      _location: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getHerbHistory(
      _batchId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[HerbTrace.HerbBatchStructOutput]>;

    herbBatches(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, string] & {
        batchId: BigNumber;
        farmerName: string;
        location: string;
        timestamp: BigNumber;
        status: string;
      }
    >;
  };

  batchCounter(overrides?: CallOverrides): Promise<BigNumber>;

  createHerbBatch(
    _farmerName: PromiseOrValue<string>,
    _location: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getHerbHistory(
    _batchId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<HerbTrace.HerbBatchStructOutput>;

  herbBatches(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, BigNumber, string] & {
      batchId: BigNumber;
      farmerName: string;
      location: string;
      timestamp: BigNumber;
      status: string;
    }
  >;

  callStatic: {
    batchCounter(overrides?: CallOverrides): Promise<BigNumber>;

    createHerbBatch(
      _farmerName: PromiseOrValue<string>,
      _location: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getHerbHistory(
      _batchId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<HerbTrace.HerbBatchStructOutput>;

    herbBatches(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, string] & {
        batchId: BigNumber;
        farmerName: string;
        location: string;
        timestamp: BigNumber;
        status: string;
      }
    >;
  };

  filters: {
    "BatchCreated(uint256,string,uint256)"(
      batchId?: null,
      farmerName?: null,
      timestamp?: null
    ): BatchCreatedEventFilter;
    BatchCreated(
      batchId?: null,
      farmerName?: null,
      timestamp?: null
    ): BatchCreatedEventFilter;
  };

  estimateGas: {
    batchCounter(overrides?: CallOverrides): Promise<BigNumber>;

    createHerbBatch(
      _farmerName: PromiseOrValue<string>,
      _location: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getHerbHistory(
      _batchId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    herbBatches(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createHerbBatch(
      _farmerName: PromiseOrValue<string>,
      _location: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getHerbHistory(
      _batchId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    herbBatches(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
